# ???
server:
  port: 9001
  servlet:
    session:
      cookie:
        http-only: false
#???
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book?useSSL=false
    username: root
    password: password


